version: '3'

services:
    devcontainer:
      env_file: .env
      image: mcr.microsoft.com/devcontainers/base:bullseye
      volumes:
        - ../..:/workspaces:cached
      network_mode: service:db
      command: sleep infinity
    db:
        env_file: .env
        image: mysql:${MYSQL_VERSION}
        restart: unless-stopped
        ports:
            - 3376:3306
        volumes:
            - db-data:/var/lib/mysql

volumes:
  db-data: